name: xml-reader

on:
  push:
    branches: main

jobs:
  test_pul_request:
    runs-on: moh_win
    
    steps:
    
      - run: |
          whoami
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run  PowerShell script
        id: run-script
        run: |
          & "C:\Logs\getallkey.ps1" -xmlPath "C:\Logs\web.setParameters.xml" -keyName "app_name"

      - name: Use script output
        run: |
          echo "Application Name: ${{ steps.run-script.outputs.keyout }}"
          
      
      
