name: xml-reader

on:
  push:
    branches: main

jobs:
  test_pul_request:
    runs-on: moh_win
    
    steps:
    
      - run: |
          whoami
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Sample append to OUT
        id: sample
        run: |
          echo "app_name_sample=worksss" >> $env:GITHUB_OUTPUT
          
      - name: Use sample script output
        run: |
          echo "Sample Application_Name: ${{ steps.sample.outputs.app_name_sample }}"          

      - name: Run  PowerShell script
        id: run-script
        run: |
          & "C:\Logs\getallkey.ps1" -xmlPath "C:\Logs\web.setParameters.xml" -keyName "app_name"
          
      - name: Assign to variable
        id: run-scriptx
        run: |
          $returnvalue=& "C:\Logs\getallkey.ps1" -xmlPath "C:\Logs\web.setParameters.xml" -keyName "app_name"
          #echo "$returnvalue" >> $env:GITHUB_OUTPUT
          "$returnvalue" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

         
      - name: Use script output
        run: |
          echo "Application _Name: ${{ steps.run-scriptx.outputs.app_name }}"
          
      
      
