name: xml-reader

on:
  push:
    branches: main

jobs:
  test_pul_request:
    runs-on: moh_win
    
    steps:
    
      - run: |
          whoami
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run  PowerShell script
        id: run-script
        run: |
          & "C:\Logs\getallkey.ps1" -xmlPath "C:\Logs\web.setParameters.xml" -keyName "app_name"
          
      - name: Assign to variable
        id: run-scriptx
        run: |
          $returnvalue=& "C:\Logs\getallkey.ps1" -xmlPath "C:\Logs\web.setParameters.xml" -keyName "app_name" 
          @chcp 65001>nul
          echo $returnvalue >> %GITHUB_OUTPUT%
        shell: cmd
         
      - name: Use script output
        run: |
          echo "Application Name: ${{ steps.run-scriptx.outputs.app_name }}"
          
      
      
