name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]


jobs:
  test_pull_request:
    runs-on: windows-latest
    
    steps:
    
      - name: Setup nginx
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: infra/nginx.conf.j2
          output_file: infra/nginx.conf
          
      - run: date
      
      
