strategy:
  matrix:
    os: [ubuntu-latest, windows-latest, macOS-latest]
    node-version: [10.x, 12.x, 14.x]

steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Build and test
    run: |
      make build
      make test
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
