name: main xml read

on:
  push:
    branches: [ master ]


jobs:

  extract_key_value:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract XML Key-Value
        id: extract-xml-value
        uses: ./.github/xml-functions.ps1
        with:
          xmlPath: ${{ env.XML_PATH }}
          key: ${{ env.KEY_NAME }}

      - name: Show Extracted Key-Value
        run: |
          echo "Extracted Key-Value: ${{ steps.extract-xml-value.outputs.value }}"

  test_pull_request:
    runs-on: windows-latest
    
    steps:

      - run: |
          "& cmd /c C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe -verb:sync -source:runcommand -dest:runcommand=\"cd C:\\inetpub\\wwwroot\\assoc.qa; \"C:\\Program Files\\nodejs\\pm2.cmd\" restart QuotingSignup-qa\",waitinterval=200000,wmsvc='https://remotehost:8172/msdeploy.axd?site=BackupSite',AuthType=Basic,userName=svc-BuildDeployDev,password='***' -allowUntrusted -verbose'"
          
      - name: Setup nginx
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: infra/nginx.conf.j2
          output_file: infra/nginx.conf
          
      - run: date
