name: ONY_THIS

on:
  push:
    branches: main
    
jobs:

  extract_key_value:
    runs-on: 'moh_win'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: actions/checkout@v3
        with:
          repository: knowyrtech/betech
          ref: feature365
          path: "${{ github.workspace }}/betech"        

      - name: Extract XML Key-Value
        id: extract-xml-value
        uses: ./betech/getxmldata.yml@feature365
#        with:
#          xmlPath: ${{ env.XML_PATH }}
#          key: ${{ env.KEY_NAME }}

      - name: Show Extracted Key-Value
        run: |
          echo "Extracted uu Key-Value: ${{ steps.extract-xml-value.outputs.value }}"
