name: main xml read

on:
  push:
    branches: main
    
jobs:

  inside_actionyml:
#    runs-on: windows-latest
    
    uses: knowyrtech/betech/.github/workflows/extractxmldata.yml@feature365
    with:
      xmlPath: ${{ env.XML_PATH }}
      key: ${{ env.KEY_NAME }}

