name: TEST  main xml read

on:
  push:
    branches: main
    
jobs:
  
  
  explicit_checkout_remote_repo:
    runs-on: windows-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Checkout remote repository
        uses: actions/checkout@v2
        with:
          repository: knowyrtech/betech  # Replace with the owner and repository name
          ref: feature365  # Replace with the branch or commit SHA you want to checkout
          path: "${{ github.workspace }}"  # Folder name for the remote repository

      - name: List files in the remote repository
        run: dir "${{ github.workspace }}"  # Example command to list files in the remote repository
    
    
  inside_actionyml:
#    runs-on: windows-latest
    
    uses: knowyrtech/betech/.github/workflows/extractxmldata.yml@feature365
    with:
      xml_Path: 'D:\myxl\setparam.xml'
      key_name: 'app_name'

